// <auto-generated/>
#nullable enable
using System;

namespace DeepEqual
{
    /// <summary>
    /// Fluent, compile-time configuration entrypoint. The generator reads calls made inside
    /// <c>DeepOpsConfig.Configure(DeepOpsBuilder b)</c> and produces the merged configuration.
    /// All methods are no-op at runtime and only record intent for Roslyn to read.
    /// </summary>
    public sealed class DeepOpsBuilder
    {
        public RootBuilder ForRoot<TRoot>(Preset preset = Preset.Default) => new(typeof(TRoot), preset);
        public ExternalBuilder ForExternal<TRoot>() => new(typeof(TRoot));

        // Global knobs (no-op at runtime, captured by generator)
        public DeepOpsBuilder StableMemberIndices(bool on = true) => this;
        public DeepOpsBuilder StringComparison(StringComparison comparison) => this;
        public DeepOpsBuilder FloatEpsilon(double eps) => this;
        public DeepOpsBuilder DecimalEpsilon(decimal eps) => this;
        public DeepOpsBuilder TreatNaNEqual(bool on = true) => this;
    }
}